# Generated by Django 5.2.18 on 2026-10-08 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Email",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gmail_message_id", models.CharField(max_length=255, unique=True)),
                ("gmail_thread_id", models.CharField(blank=True, max_length=255)),
                ("from_email", models.CharField(max_length=320)),
                ("from_name", models.CharField(blank=True, max_length=255)),
                ("to_email", models.CharField(blank=True, max_length=320)),
                ("subject", models.TextField(blank=True)),
                ("body_text", models.TextField(blank=True)),
                ("body_clean", models.TextField(blank=True)),
                ("attachments", models.JSONField(blank=True, default=list)),
                ("received_at", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("received", "Received"),
                            ("triaged", "Triaged"),
                            ("needs_review", "Needs Review"),
                            ("awaiting_approval", "Awaiting Approval"),
                            ("approved", "Approved"),
                            ("done", "Done"),
                            ("rejected", "Rejected"),
                            ("failed", "Failed"),
                            ("ignored", "Ignored"),
                        ],
                        db_index=True,
                        default="received",
                        max_length=32,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("quote_request", "Quote Request"),
                            ("booking", "Booking"),
                            ("shipment_status", "Shipment Status"),
                            ("paperwork", "Paperwork"),
                            ("claim", "Claim"),
                            ("other", "Other"),
                        ],
                        max_length=32,
                        null=True,
                    ),
                ),
                (
                    "urgency",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("low", "Low"),
                            ("normal", "Normal"),
                            ("high", "High"),
                        ],
                        max_length=16,
                        null=True,
                    ),
                ),
                ("needs_review_reason", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-received_at"],
            },
        ),
        migrations.CreateModel(
            name="EvalRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("dataset_version", models.CharField(blank=True, max_length=64)),
                ("model_classify", models.CharField(blank=True, max_length=100)),
                ("model_extract", models.CharField(blank=True, max_length=100)),
                ("metrics", models.JSONField(blank=True, default=dict)),
                ("report_path", models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name="Playbook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "company_name",
                    models.CharField(default="Indus Freight", max_length=255),
                ),
                (
                    "signature",
                    models.TextField(default="Best regards,\nOps Team\nIndus Freight"),
                ),
                ("tone", models.TextField(default="Friendly, brief and professional.")),
                ("facts", models.TextField(blank=True)),
                ("never_promise", models.TextField(blank=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("updated_by", models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Draft",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject", models.TextField(blank=True)),
                ("body", models.TextField()),
                ("asks_for", models.JSONField(blank=True, default=list)),
                ("ok", models.BooleanField(default=True)),
                ("blocked_reason", models.TextField(blank=True)),
                ("model", models.CharField(blank=True, max_length=100)),
                ("input_tokens", models.IntegerField(default=0)),
                ("output_tokens", models.IntegerField(default=0)),
                (
                    "cost_usd",
                    models.DecimalField(decimal_places=6, default=0, max_digits=10),
                ),
                ("latency_ms", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "email",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="drafts",
                        to="inbox.email",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Approval",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[("slack", "Slack"), ("dashboard", "Dashboard")],
                        max_length=16,
                    ),
                ),
                ("reviewer", models.CharField(blank=True, max_length=255)),
                (
                    "decision",
                    models.CharField(
                        choices=[
                            ("approved", "Approved"),
                            ("edited", "Edited"),
                            ("rejected", "Rejected"),
                        ],
                        max_length=16,
                    ),
                ),
                ("final_body", models.TextField(blank=True)),
                ("decided_at", models.DateTimeField(auto_now_add=True)),
                (
                    "email",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approvals",
                        to="inbox.email",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Action",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("hubspot_contact", "HubSpot contact"),
                            ("hubspot_deal", "HubSpot deal"),
                            ("hubspot_task", "HubSpot task"),
                            ("hubspot_note", "HubSpot note"),
                            ("shipmatch_upload", "ShipMatch upload"),
                            ("shipmatch_lookup", "ShipMatch lookup"),
                            ("slack_alert", "Slack alert"),
                            ("reply_sent", "Reply sent"),
                        ],
                        max_length=32,
                    ),
                ),
                ("idempotency_key", models.CharField(max_length=255, unique=True)),
                ("request", models.JSONField(blank=True, default=dict)),
                ("response", models.JSONField(blank=True, default=dict)),
                ("ok", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "email",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actions",
                        to="inbox.email",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Failure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("workflow", models.CharField(blank=True, max_length=255)),
                ("node", models.CharField(blank=True, max_length=255)),
                ("error", models.TextField(blank=True)),
                ("execution_id", models.CharField(blank=True, max_length=100)),
                ("resolved", models.BooleanField(default=False)),
                ("retried_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "email",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="failures",
                        to="inbox.email",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Triage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("quote_request", "Quote Request"),
                            ("booking", "Booking"),
                            ("shipment_status", "Shipment Status"),
                            ("paperwork", "Paperwork"),
                            ("claim", "Claim"),
                            ("other", "Other"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "urgency",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("normal", "Normal"),
                            ("high", "High"),
                        ],
                        max_length=16,
                    ),
                ),
                ("confidence", models.FloatField()),
                ("reason", models.TextField(blank=True)),
                ("fields", models.JSONField(blank=True, default=dict)),
                ("field_confidence", models.JSONField(blank=True, default=dict)),
                ("missing_fields", models.JSONField(blank=True, default=list)),
                ("flags", models.JSONField(blank=True, default=list)),
                ("injection_flag", models.BooleanField(default=False)),
                ("route", models.CharField(default="review", max_length=16)),
                ("review_reason", models.TextField(blank=True)),
                ("model_classify", models.CharField(blank=True, max_length=100)),
                ("model_extract", models.CharField(blank=True, max_length=100)),
                ("input_tokens", models.IntegerField(default=0)),
                ("output_tokens", models.IntegerField(default=0)),
                (
                    "cost_usd",
                    models.DecimalField(decimal_places=6, default=0, max_digits=10),
                ),
                ("latency_ms", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "email",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="triages",
                        to="inbox.email",
                    ),
                ),
            ],
        ),
    ]
