# Generated by Django 5.2.18 on 2026-10-08 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inbox", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="email",
            name="references",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="email",
            name="reply_to",
            field=models.CharField(blank=True, max_length=320),
        ),
        migrations.AddField(
            model_name="email",
            name="rfc_message_id",
            field=models.CharField(blank=True, max_length=998),
        ),
    ]
