# Generated by Django 5.2.18 on 2026-10-08 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inbox", "0002_email_rfc_headers"),
    ]

    operations = [
        migrations.AddField(
            model_name="email",
            name="last_execution_id",
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
    ]
